modLoader="javafml" #mandatory

loaderVersion="[33,)"

license="All rights reserved"

[[mods]] #mandatory

modId="elementalmastery" #mandatory

version="1.16.2-0.1.1" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/elemental-mastery" #optional

displayName="Elemental Mastery" #mandatory

description='''
Adds 4 gems with multiple purposes
Check Curse Forge for more information
'''

[[dependencies.elementalmastery]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33.0.0,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"